language: scala
jdk:
- oraclejdk8
scala:
- 2.12.2
deploy:
  provider: heroku
  api_key:
    secure: GwyY5TEaHZ5vpUAHDH2PHNlegOs9wRC6u0F1Iv9aPNRRZRT1Q/+ErSW0EgWovPNb+zKqYXgOVKu8gdo9GPkkdGkCjVlRX+XjLmJUC4EwUaKnHofVGpvCZpN8L9yUsiMJSIj8m0FCsr8RjGfvyCghYghnvaS4l+YtqVjwFbqihx0KAZcCJrJ5KStzW1vmOq15LZNggVGOBgTPH1MC4ZhovLQmRVXFZMOV+l2T59P8LxJ1pA6JsSr2y6t5o1ptYf3KP65KBv5DOEjAYyoyR7aOhVNY5qor0I/vshU+qygMEW6kOt5tM0fX05RvQ486BZLBAxymhyz1yuRVquQWfr/Taoix/5wfOttyG0zpzzM3uUlbeiJzz+7funEhEIgzbz4px9AO4XzHVA1m43egKhCK7p9QfhO5kgdgqsJIV3LH1X8AB92xttnxebrY8hSShVUWqoVRbJPaFMnWrochjxL6zUKbsZxdwqLBbEqM49dHbSmUSbBSEa2wRCsMlEANP7a7P2quHVmAaj5PtE0efR/ADzoHpTQv6FSeQd63wjhTxpWHBgekTkBj8TdF+zBg+BrMIvqZ1P9qEsOYP3HmEiNELU+IHo3oVABS50zBUSsmTugezWf5KIJbps0EmLl6DSiigaw0H4fG1pJ/PpWoRPHEpSfvL+LVAJ79YzPbT/z5TT8=
  app: sassetzero
  on:
    repo: nikhosagala/sasset
    branch: staging
notifications:
  email: false
  slack:
    secure: ZkQS9Vf+ExFtrYy62I/4rcr3P0DWOyp9GHuDkd/lN1fwf1fq/hL10TBhV0hXAeN6i0MtHqEM3bE7Uc5couLrfexPP6hstPKusaDhoHurzlqUz2BCc6AQ25Z3zW4dZOobo5jAxy4EQhib5QZ03S0hZ9sPT3g7hsks2dZlHMQSbaLlW/2dZFGuEz3I77PqT6Z0w0BDIiXWoyzjDiRr/1C4k13OLlwaJfQ+g3UXBh+LNK0MeziA+T8hSkPyOFHIbdQEAzRr6Y5vGNdyqpFDXd1DBsLGn4uH+vuIaeyKKPoVa7HjZ+bBfkFTVdo4fg/TL5XVQ7zbR7+mWcombDTZoWtlPg2CbmB00fkujE5r0jHsT9uQlhgC71lNHs64pjaF+qnOMYVDrAyqsFhru+UHsWbjmKSBUTDVLF0cAJReDPz/Ic9wVf0yVyicE4dTc+Ob7D0/eS6JLMSa3Vf01jgXRgyGqKb1w4wzHhVr1XpJs6U5vNI9JIuWW2PL4lrpF4590cOnexNkHHu7Iox6SvaUaUz1RiwZO+jsrS3MhH51O+3PSflAVvPn7sttHNvxRp8ppSuJ8qlrKZuTOyvPr7A+NQ0mvPziUFwEQyXQNZi3TWCIrxWWoQn3AFJJrC4hNX/20yLQwSUSgYwM1Cxa/LYrZ9m/7rVMMWm5fWU1C/lhkeZHWzM=
