language: scala
jdk:
- oraclejdk8
scala:
- 2.12.2

deploy:
  provider: heroku
  api_key:
    secure: jxwR8xYSBey2Bu+D0Gt4vuIbWjLkAJjfX4GqwpUS+13hxQXUEr6hMSsk8cZnR+GYOopeldVLQJ7N/CkHvfAGNi/+LzZwx9G2JCPUTPWCUnzmuWRlI5PXOoTTVR2S3dumU/KBnvN1lNMdj5WrJds8VeTmlsLgULoSRZog6VG0KlPpYDxCkOpZ/d2hJS8OpmkXmCFPJjwPBcHW/QmSw+A0biWlKvnzb/N3u26SLn2Wtmms0o44yfkB+nLn9i6F5IW6Bt6mR2ZKF/+CWIi1sjdDDTmYuO2ugj4A/kK3sYj8x+HZOJ7/urXglmwEzWoCoJfkEagyHXofNylQIxWJxbIwTZMDSilHIwVpMbQn1gsb4LbI12uMnQFeaO/pMNlZJYNE60sjktPfBSesjL/a0txPaGs8itx1ABwGDPJsIzS+2UpNsME1FQKM4Xnff2waxGvNVOgd3wdKUOMXCqTzVmEbkriT1A04DGzA4kY6NVDIGhk9RBVOdEpWFK9nrvoYuxzATRYFTWwwQzIshLpL8iAhKcvAw7rZv0+NtCjvpGTAxkIn3XdNevr4TQxNr9OhEPqbbnmSO8W3g+V2TP8zhGXSIX+27A6kA7w0gnkKTG1yhbSeKcd6mnRAzSK4Stibiq/IVJQ0cOqoZ5tlF4D0LbUbiZRjc0V2kwjvDXN3Nvuw1rw=
  app: fam-asset
  on:
    repo: nikhosagala/fam
    branch: staging

notifications:
  email: false
  slack:
    secure: ZkQS9Vf+ExFtrYy62I/4rcr3P0DWOyp9GHuDkd/lN1fwf1fq/hL10TBhV0hXAeN6i0MtHqEM3bE7Uc5couLrfexPP6hstPKusaDhoHurzlqUz2BCc6AQ25Z3zW4dZOobo5jAxy4EQhib5QZ03S0hZ9sPT3g7hsks2dZlHMQSbaLlW/2dZFGuEz3I77PqT6Z0w0BDIiXWoyzjDiRr/1C4k13OLlwaJfQ+g3UXBh+LNK0MeziA+T8hSkPyOFHIbdQEAzRr6Y5vGNdyqpFDXd1DBsLGn4uH+vuIaeyKKPoVa7HjZ+bBfkFTVdo4fg/TL5XVQ7zbR7+mWcombDTZoWtlPg2CbmB00fkujE5r0jHsT9uQlhgC71lNHs64pjaF+qnOMYVDrAyqsFhru+UHsWbjmKSBUTDVLF0cAJReDPz/Ic9wVf0yVyicE4dTc+Ob7D0/eS6JLMSa3Vf01jgXRgyGqKb1w4wzHhVr1XpJs6U5vNI9JIuWW2PL4lrpF4590cOnexNkHHu7Iox6SvaUaUz1RiwZO+jsrS3MhH51O+3PSflAVvPn7sttHNvxRp8ppSuJ8qlrKZuTOyvPr7A+NQ0mvPziUFwEQyXQNZi3TWCIrxWWoQn3AFJJrC4hNX/20yLQwSUSgYwM1Cxa/LYrZ9m/7rVMMWm5fWU1C/lhkeZHWzM=
