language: scala
jdk:
- oraclejdk8
scala:
- 2.12.2
deploy:
  provider: heroku
  api_key:
    secure: I2HSn6lXAh3fZjlkOMPbPOeRXmvZMBJi1lwmhWadOATGSnUpmWRSD8CVUlx11VfCMIBfIOv1Dc5ddh3pa1WlUz/oog+P6SxrRBP8BlC2nbJ9sduOn4vjDPkZuzyAwIHRGRnhj/7Ixf/WsR83Ib9AKAorpDWIThE8+K3/7l5k7XZ1S6imllwNIsR+LzqbPFq5g8fT9mBvPcBIcyKNLOPoEcmIrS8qjx4MuBL6p8RS/3HOtw/PkDZcARx5Zf3+tnNWnWIbFPw30Ugbem9TH/FPUdTMN6iE0y7rCe60ScHrGlVYje6u42mbCAdX9qJyKNrK/94+C+aWQgzTgTrGjrZqnjsrKpfGQoqBML9qhQBsM8EnBPQ1m8ZvS5PTHL/TiLY06mwfYAfNy1uVrzOgyt4bIBnSYJKfdeTukW+fX1CJoV7I2VWXIVeM6kzaX6+19laqzx+Hyt9FF6FljBEGdZwbsCB72k+WLY4s4Lqr+lP+Wix5YRCosz5ebZMcqxCRaTp4ltyW2PSmoAWpTA66vyjQ07LkJMNGHAifJMYau73M9XfUUGjX9RqXOqHe/6htJZHh9nV7GU77/ZA+gpXWqMaLqtkpJZCHUVUKcrUE/1qr6dxIl+Xped3sQdBBm/E2eOnbBpQM+UDjDsyliHVWmwm8IjdjAp9xAv58u5YxsN31sqY=
  app: sassetzero
  on:
    repo: nikhosagala/sasset
    branch: staging
notifications:
  email: false
  slack:
    secure: ZkQS9Vf+ExFtrYy62I/4rcr3P0DWOyp9GHuDkd/lN1fwf1fq/hL10TBhV0hXAeN6i0MtHqEM3bE7Uc5couLrfexPP6hstPKusaDhoHurzlqUz2BCc6AQ25Z3zW4dZOobo5jAxy4EQhib5QZ03S0hZ9sPT3g7hsks2dZlHMQSbaLlW/2dZFGuEz3I77PqT6Z0w0BDIiXWoyzjDiRr/1C4k13OLlwaJfQ+g3UXBh+LNK0MeziA+T8hSkPyOFHIbdQEAzRr6Y5vGNdyqpFDXd1DBsLGn4uH+vuIaeyKKPoVa7HjZ+bBfkFTVdo4fg/TL5XVQ7zbR7+mWcombDTZoWtlPg2CbmB00fkujE5r0jHsT9uQlhgC71lNHs64pjaF+qnOMYVDrAyqsFhru+UHsWbjmKSBUTDVLF0cAJReDPz/Ic9wVf0yVyicE4dTc+Ob7D0/eS6JLMSa3Vf01jgXRgyGqKb1w4wzHhVr1XpJs6U5vNI9JIuWW2PL4lrpF4590cOnexNkHHu7Iox6SvaUaUz1RiwZO+jsrS3MhH51O+3PSflAVvPn7sttHNvxRp8ppSuJ8qlrKZuTOyvPr7A+NQ0mvPziUFwEQyXQNZi3TWCIrxWWoQn3AFJJrC4hNX/20yLQwSUSgYwM1Cxa/LYrZ9m/7rVMMWm5fWU1C/lhkeZHWzM=
