language: scala
jdk:
- oraclejdk8
scala:
- 2.12.2
deploy:
  provider: heroku
  api_key:
    secure: kvhN1S8gRMcbkTwqvlo73v1evHVEru0Qb9CahHIB8n/vTfdo1KtaI54Zq2VnELIT1epA+hCa3OSACmkudGwGGo4FJjoryJykPf4BbgzRfxyPGMgyPPSUrxq6V4X+jlucOu017OqefQZTKumLel++0dY8hkP1/tGYaLQ+bjKUx0pq3MR+N+heStUZlEORqHr8982iYvhI16oj4G61fNBySySv+BnJ9SAIQM42yKEU+3iys5V0JFvF2T/lvvjHXsQwVF1jzJIKfnk3BOAUDMGj3Fjfly7KchrfZfGMzPxFLYIgQmLfOYT5J9UHc2Dqmmh9+gsWgAAXfzhIP4vv30eRPFhOz5Wu71y6wsrFZh+VvPBy4mht+dBRT2l8nEC6qx71cQatujMMSQep3jnRGT2en7HYoJdn/sdejjSN3cgIDfau62Ey27FPgWRkxbPSbyba7UXDlKQmWKtpXb/IzmDHcKcyiTBfxxTmOW2z42jE1OefEG5QqFBwTtR191UJMNVQD8sb2Zpxd/wpKbUs7PipuxeUGdZPGjQKWt4MNJPVxcnqRS/LMhSzML2pWF28LY8GmdD4H3dKVHNvfHc9v7EIVWveTMQDElygsSJUw7MkmXJ9s1VrCi+ddIwV4mWFlc/+4nv3rUOZ4OJ4IyWV3mRscXwH+4ccp5EFV64hHY2hOYE=
  app: sassetzero
  on:
    repo: nikhosagala/sasset
    branch: staging
notifications:
  email: false
  slack:
    secure: ZkQS9Vf+ExFtrYy62I/4rcr3P0DWOyp9GHuDkd/lN1fwf1fq/hL10TBhV0hXAeN6i0MtHqEM3bE7Uc5couLrfexPP6hstPKusaDhoHurzlqUz2BCc6AQ25Z3zW4dZOobo5jAxy4EQhib5QZ03S0hZ9sPT3g7hsks2dZlHMQSbaLlW/2dZFGuEz3I77PqT6Z0w0BDIiXWoyzjDiRr/1C4k13OLlwaJfQ+g3UXBh+LNK0MeziA+T8hSkPyOFHIbdQEAzRr6Y5vGNdyqpFDXd1DBsLGn4uH+vuIaeyKKPoVa7HjZ+bBfkFTVdo4fg/TL5XVQ7zbR7+mWcombDTZoWtlPg2CbmB00fkujE5r0jHsT9uQlhgC71lNHs64pjaF+qnOMYVDrAyqsFhru+UHsWbjmKSBUTDVLF0cAJReDPz/Ic9wVf0yVyicE4dTc+Ob7D0/eS6JLMSa3Vf01jgXRgyGqKb1w4wzHhVr1XpJs6U5vNI9JIuWW2PL4lrpF4590cOnexNkHHu7Iox6SvaUaUz1RiwZO+jsrS3MhH51O+3PSflAVvPn7sttHNvxRp8ppSuJ8qlrKZuTOyvPr7A+NQ0mvPziUFwEQyXQNZi3TWCIrxWWoQn3AFJJrC4hNX/20yLQwSUSgYwM1Cxa/LYrZ9m/7rVMMWm5fWU1C/lhkeZHWzM=
